name: raf_airlines_client
description: Mobile application for passenger of RAF Airlines to view and book their flights

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 6.1.1
  get_it: 5.0.3
  equatable: 1.2.5
  dio: 3.0.10
  shared_preferences: 0.5.12+4
  intl: 0.16.1
  simple_animations: 2.4.2
  google_fonts: 1.1.1
  dotted_decoration: 1.2.2
  flutter_spinkit: 4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/raf.png

  fonts:
    - family: Axiforma
      fonts:
        - asset: fonts/Axiforma-Regular.ttf
        - asset: fonts/Axiforma-Italic.ttf
          style: italic
